### ISSUE TITLE
right-padding with shinydashboard sidebar

### ISSUE THREAD

**Issue by samssann** [merlinoa/shinyFeedback#53]
I have a selectizeInput set in the sidebar of a shinydashboard. Even though the icon is set to NULL, it still produces a right-padding, which I can't seem to get rid of. This line is responsible 

```css
.has-feedback .form-control {
    padding-right: 42.5px;
}
```
![image](https://user-images.githubusercontent.com/19807339/99840786-ddf63400-2b75-11eb-8ad8-0785a2181c79.png)

![image](https://user-images.githubusercontent.com/19807339/99840706-bb641b00-2b75-11eb-806b-d10f5651994d.png)

Any ideas on how to disable this feature?
